### ISSUE TITLE
Error in BundleTransformer when using "?explicit" in scss import directive

### ISSUE THREAD

**Issue by iherwald** [smartstoreag/SmartStoreNET#1275]
In v2.x for importing a default stylesheet file (LESS) into the custom.less stylesheet of a derived theme, documentation recommends to add "?explicit" to the import directive:
http://docs.smartstore.com/display/SMNET25/How+to+write+a+Theme

In v3.0.3, when importing a default stylesheet (SCSS) file from the parent theme (FLEX) into the _custom.scss of a derived theme, BundleTransformer throws an exception:
```
@import "../../Flex/Content/_artlist.scss?explicit";

.art-description {
    // At least 4 lines height for description
    height: ($art-font-size-sm * $art-line-height) * 4 !important;
}
```
```
BundleTransformer.Core.Translators.AssetTranslationException was unhandled by user code
  HResult=-2146233088
  Message=During translation of SCSS-code, readed from the file '/Themes/Flex/Content/theme.scss', to CSS-code syntax error has occurred. 
See more details:

Message: It's not clear which file to import for '@import "../../Flex/Content/_artlist.scss?explicit"'.
Candidates:
  ../../Flex/Content/_artlist.scss?explicit.scss
  ../../Flex/Content/_artlist.scss?explicit.css
Please delete or rename all but one of these files.

File: /Themes/Flex/Content/_custom.scss
Line number: 6
Column number: 1
Source fragment:

Line 6: @import "../../Flex/Content/_artlist.scss?explicit";

```

**Comment by muratcakir** [comment]
It's fixed now... was a glitch in the libSass library.

Though the way you use the `?explicit` directive is not what it's made for: there's no need to import anything in `_custom.scss`. The directive is only necessary when you overwrite a file, which already contains content. `?explicit` pulls the content of the overwritten file virtually into your file. This way, you don't have to redeclare everything.

**Comment by iherwald** [comment]
Thank you for fixing and clarification!

**Comment by asdword** [comment]
Smart Store v4 :
install **LibSassHost.Native.win-x86** in StartStore.Web.Framework project

**Comment by Akinnagbe** [comment]
Hello,

I have the package installed but I am still getting the error below:

During translation of SCSS code, readed from the file '/Themes/Flex/Content/theme.scss', to CSS code syntax error has occurred. 
See more details:

EndlessExtendError: Extend is creating an absurdly big selector, aborting!
        on line 68:9 of Themes/Flex/Content/theme.scss
>> .btn.btn-to-danger {
   ^

Error code: 1
Description: Extend is creating an absurdly big selector, aborting!
File: /Content/shared/_buttons.scss
Line number: 472
Column number: 1
Source fragment:

Line 472: .btn.btn-to-danger {
----------^
Line 473:     &:not([disabled]):not(.disabled):hover {
